GITHUB_QUERIES = {
    "Python": ("language:Python", "python"),
    "Java": ("language:Java", "java"),
    "JavaScript": ("language:JavaScript", "javascript"),
    "TypeScript": ("language:TypeScript", "typescript"),
    "C++": ("language:C++", '"C++"'),
    "C#": ("language:C#", '"C#"'),
    "C": ("language:C", '"C"'),
    "Go": ("language:Go", "golang OR go"),
    "Rust": ("language:Rust", "rust"),
    "Ruby": ("language:Ruby", "ruby"),
    "R": ("language:R", '"R language" OR rstats'),
    "Kotlin": ("language:Kotlin", "kotlin"),
    "SQL": ("sql", "sql"),
    "PostgreSQL": ("postgresql OR postgres", "postgresql OR postgres"),
    "MySQL": ("mysql", "mysql"),
    "MongoDB": ("mongodb", "mongodb"),
    "MongoDB Atlas": ('"MongoDB Atlas"', '"MongoDB Atlas"'),
    "Redis": ("redis", "redis"),
    "React": ("react", "react"),
    "Next.js": ("nextjs OR next.js", "nextjs OR next.js"),
    "Node.js": ("nodejs OR node.js", "nodejs OR node.js"),
    "HTML": ("html", "html"),
    "CSS": ("css", "css"),
    "Tailwind CSS": ('"tailwind css" OR tailwindcss', '"tailwind css" OR tailwindcss'),
    "Material UI": ('"material ui" OR mui', '"material ui" OR mui'),
    "Spring": ("spring-framework OR spring-boot", "spring OR spring-boot"),
    ".NET": (".net OR dotnet", ".net OR dotnet"),
    "Android": ("android", "android"),
    "iOS": ("ios", "ios"),
    "AWS": ("aws OR amazon-web-services", "aws OR amazon-web-services"),
    "GCP": ("gcp OR google-cloud", "gcp OR google-cloud"),
    "Azure": ("azure", "azure"),
    "Docker": ("docker", "docker"),
    "Kubernetes": ("kubernetes OR k8s", "kubernetes OR k8s"),
    "Terraform": ("terraform", "terraform"),
    "Linux": ("linux", "linux"),
    "Git": ("git", "git"),
    "GitHub": ("github", "github"),
    "GitHub Actions": ('"github actions"', '"github actions"'),
    "Apache Kafka": ("kafka", "kafka"),
    "Apache Spark": ("spark", "spark"),
    "Airflow": ("airflow", "airflow"),
    "PyTorch": ("pytorch", "pytorch"),
    "scikit-learn": ("scikit-learn OR sklearn", "scikit-learn OR sklearn"),
    "Jupyter": ("jupyter", "jupyter"),
    "OpenAI": ("openai", "openai"),
    "GPT": ("gpt", "gpt"),
    "Claude": ("claude", "claude"),
    "MCP": ('"model context protocol" OR mcp', '"model context protocol" OR mcp'),
    "GraphQL": ("graphql", "graphql"),
    "gRPC": ("grpc", "grpc"),
    "REST": ("rest api", "rest api"),
    "Figma": ("figma", "figma"),
    "Tableau": ("tableau", "tableau"),
    "Salesforce": ("salesforce", "salesforce"),
    "Cloudflare": ("cloudflare", "cloudflare"),
    "Cloudflare Workers": ('"cloudflare workers"', '"cloudflare workers"'),
    "dbt": ("dbt", "dbt"),
    "Amazon S3": ('"amazon s3" OR s3', '"amazon s3" OR s3'),
}


STACKOVERFLOW_TAGS = {
    "Python": "python", "AWS": "amazon-web-services", "Kubernetes": "kubernetes",
    "Go": "go", "GCP": "google-cloud-platform", "SQL": "sql",
    "TypeScript": "typescript", "Azure": "azure", "Java": "java",
    "C++": "c++", "JavaScript": "javascript", "Rust": "rust",
    "React": "reactjs", "Claude": "claude", "Terraform": "terraform",
    "Linux": "linux", "GPT": "openai-api", "Node.js": "node.js",
    "PostgreSQL": "postgresql", "Docker": "docker", "Apache Spark": "apache-spark",
    "Apache Kafka": "apache-kafka", "PyTorch": "pytorch",
    "OpenAI Codex": "openai-codex", "MongoDB Atlas": "mongodb-atlas",
    "Airflow": "airflow",
    "GitHub": "github", "Ruby": "ruby", "C#": "c#", "MCP": "model-context-protocol",
    "Grafana": "grafana", "TensorFlow": "tensorflow", "Android": "android",
    "Bash": "bash", "Git": "git", "Prometheus": "prometheus", "iOS": "ios",
    "Anthropic": "anthropic", "MySQL": "mysql", "Redis": "redis",
    "Datadog": "datadog", "MongoDB": "mongodb", "Cloudflare": "cloudflare",
    "Salesforce": "salesforce", "Swift": "swift", "Apache Flink": "apache-flink",
    "Snowflake": "snowflake-cloud-data-platform", "GraphQL": "graphql",
    "Scala": "scala", "JAX": "jax", "dbt": "dbt", "BigQuery": "google-bigquery",
    "CUDA": "cuda", "Kotlin": "kotlin", "REST": "rest",
    "GitHub Copilot": "github-copilot", "R": "r", "C": "c",
    "ClickHouse": "clickhouse", "Transformers": "huggingface-transformers",
    "Ansible": "ansible", "Figma": "figma", "gRPC": "grpc", "CSS": "css",
    "Next.js": "next.js", "LangChain": "langchain", "Helm": "kubernetes-helm",
    "Databricks": "databricks", "Jira": "jira", "Lua": "lua",
    "Elasticsearch": "elasticsearch", "Amazon S3": "amazon-s3", "HTML": "html",
    "GitHub Actions": "github-actions", "Cloudflare Workers": "cloudflare-workers",
    "Amazon EKS": "amazon-eks", "Hadoop": "hadoop", "Tableau": "tableau",
    "Zendesk": "zendesk", "Pandas": "pandas", "Okta": "okta",
    "Apache Iceberg": "apache-iceberg", "Splunk": "splunk", "Assembly": "assembly",
    "Bazel": "bazel", "Gradle": "gradle", "Cassandra": "cassandra",
    "Pulumi": "pulumi", "Trino": "trino", "Buildkite": "buildkite",
    "Jenkins": "jenkins", "Dagster": "dagster", "Redux": "redux", "Looker": "looker",
    "OpenTelemetry": "open-telemetry", "Envoy": "envoyproxy",
    "Ruby on Rails": "ruby-on-rails", "Triton Inference Server": "triton-inference-server",
    "AWS CloudFormation": "amazon-cloudformation", "NetSuite": "netsuite",
    "FastAPI": "fastapi", "SwiftUI": "swiftui", "CockroachDB": "cockroachdb",
    "Puppet": "puppet", "PHP": "php", "Google GKE": "google-kubernetes-engine",
    "DynamoDB": "amazon-dynamodb", "Objective-C": "objective-c", "GitLab": "gitlab",
    "Spring": "spring", "RabbitMQ": "rabbitmq", "ArgoCD": "argocd",
    "Express": "express", "Vue.js": "vue.js", "Flask": "flask",
    "React Native": "react-native", "Vault": "hashicorp-vault",
    "Hugging Face": "huggingface", "WebAssembly": "webassembly", "Snyk": "snyk",
    ".NET": ".net", "SAS": "sas", "Confluence": "confluence", "NCCL": "nccl",
    "Dependabot": "dependabot", "Istio": "istio", "OpenShift": "openshift",
    "Slurm": "slurm", "Gemini": "google-gemini", "NumPy": "numpy", "UIKit": "uikit",
    "scikit-learn": "scikit-learn", "Perl": "perl", "Jupyter": "jupyter-notebook",
    "Vertex AI": "google-cloud-vertex-ai", "Angular": "angular",
    "Amazon EC2": "amazon-ec2", "Nix": "nix", "GitLab CI": "gitlab-ci",
    "CircleCI": "circleci", "SQLite": "sqlite", "Webpack": "webpack",
    "Redshift": "amazon-redshift", "Elixir": "elixir", "Llama": "llama",
    "HubSpot": "hubspot", "Tailwind CSS": "tailwind-css", "Vite": "vite",
    "MATLAB": "matlab", "Jetpack Compose": "android-jetpack-compose", "GDB": "gdb",
    "NestJS": "nestjs", "Nginx": "nginx", "Kibana": "kibana", "Vanta": "vanta",
    "Svelte": "svelte", "Streamlit": "streamlit", "Heroku": "heroku",
    "Vercel": "vercel", "Power BI": "powerbi", "MobX": "mobx",
    "SystemVerilog": "system-verilog", "Starlark": "starlark", "Plotly": "plotly",
    "Sass": "sass", "ESLint": "eslint", "Django": "django", "Cypress": "cypress",
    "Firestore": "google-cloud-firestore", "Zookeeper": "apache-zookeeper",
    "Julia": "julia", "PyTest": "pytest", "Groovy": "groovy", "Neo4j": "neo4j",
    "XGBoost": "xgboost", "Cypher": "cypher", "Postman": "postman",
    "Bicep": "azure-bicep", "Solidity": "solidity", "VBA": "vba",
    "SolidJS": "solidjs", "styled-components": "styled-components", "Gatsby": "gatsby",
    "Fly.io": "fly.io", "Laravel": "laravel", "Haskell": "haskell", "Zig": "zig",
    "Deno": "deno", "IIS": "iis", "TeamCity": "teamcity", "GLSL": "glsl",
    "Lucene": "lucene", "MLflow": "mlflow", "Apache Pulsar": "apache-pulsar",
    "Flutter": "flutter", "Babel": "babeljs", "Selenium": "selenium",
    "Material UI": "material-ui", "Storybook": "storybook", "TanStack": "tanstack-query",
}
